### ISSUE TITLE
add support for UEFI

### ISSUE THREAD

**Issue by jumanjiman** [ISEexchange/tftp#9]
references:
- http://docs.fedoraproject.org/en-US/Fedora/21/html/Installation_Guide/pxe-bootloader.html
- https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Installation_Guide/s1-netboot-pxe-config-efi.html
- http://projects.theforeman.org/projects/foreman/wiki/PXE_Booting_UEFI

**Comment by jumanjiman** [comment]
@mazad01 (public) we need to get your internal work on this into this repo and merge with https://github.com/kelseyhightower/coreos-ipxe-server if possible

**Comment by mazad01** [comment]
Sure thing, as soon as I get it up and running.

**Comment by jumanjiman** [comment]
https://github.com/jumanjihouse/hooktftp-runtime supercedes this repo
